### ISSUE TITLE
Middle clicking on titles in the library should open in new tab

### ISSUE THREAD

**Issue by dakrk** [OpenShopChannel/Website#12]
For links and buttons that send you to other pages, you'd usually expect to be able to middle click them to open them in a new tab. However, currently middle clicking them instead scrolls the page as it would if you middle clicked any non interactable part of the page, causing trying to look at multiple apps more of a pain.
(Infact, I think the title grid should be revamped as a whole, it doesn't look as pretty as the rest of the page)

**Comment by dakrk** [comment]
(oops i pressed enter early)

**Comment by Artuto** [comment]
I believe this is because it is not a real link:

https://github.com/OpenShopChannel/Website/blob/master/templates/pages/newlibrary.html#L112-L113

Don't know what could be done there...

**Comment by dakrk** [comment]
Yeah, I noticed that. Ideally it should just be an anchor instead and the href is set to the relevant URL (but I've never actually touched this so I don't know the best approach for that)
